### ISSUE TITLE
Your use of logging.info is incorrect

### ISSUE THREAD

**Issue by nzjrs** [khooihzhz/coingecko-python#1]
Using the root logger is bad practice and makes it impossible to cleanly filter out your log messages in a more complex application.

https://github.com/khooihzhz/coingecko-python/blob/2f189561aa7f5eab26e35e7bda0a796b1e23e92d/coingecko/api/base.py#L23

You should use a configured and namespaced logger like

`logging.getLogger('coingecko-python').info('message')`

**Comment by khooihzhz** [comment]
Thanks, will include this in the next version update!

**Comment by khooihzhz** [comment]
Added on v0.14 release, Thanks for raising this up again! 🙏 

```
logger = logging.getLogger('coingecko-python')
```
